### ISSUE TITLE
GPU out of memory

### ISSUE THREAD

**Issue by MarSaKi** [amjltc295/Free-Form-Video-Inpainting#1]
Hi, thanks you work!
I test your pretrained model on my dataset . (608*544 per frame) when I just put 11 frame in test folder , it can get good performance . But when I put more frames (like 30 , 1441 frames), it's GPU out of memory , what's the problem?

Thanks,

**Comment by amjltc295** [comment]
As it says, the problem is that your GPU does not have enough memory. Our model would take all frames so the GPU memory consumption is proportional to the video length. You could consider splitting it to several batches (with some overlapping), use a larger GPU or modify the code yourself.

**Comment by facetohard** [comment]
How do I train GAN If I split the video frame into several batches? G:D = 1:1 or G:D = 1:n, n means that n* batches is equal to num of all  frames in a video.

**Comment by amjltc295** [comment]
> How do I train GAN If I split the video frame into several batches? G:D = 1:1 or G:D = 1:n, n means that n* batches is equal to num of all frames in a video.

I don't quite understand your question. The inference is different from training. You could split a video to several clips and view them as different data in different batches during training (it would cause some bias though).
