### ISSUE TITLE
Broken code

### ISSUE THREAD

**Issue by bornabesic** [amjltc295/Free-Form-Video-Inpainting#10]
I am having a problem with the following line:
[https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/networks.py#L74](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/networks.py#L74)

where

[https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/networks.py#L66](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/networks.py#L66)

Since `AttentionDownSampleModule` is the basically the same class as `DownSampleModule`, its `forward()` method returns a tuple of size 3.

[https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/modules.py#L93](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/modules.py#L93)

[https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/modules.py#L90](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/modules.py#L90)

However, the `RefineNet.forward()` is trying to unpack a tuple of size 2 and I get `ValueError: too many values to unpack (expected 2)`.

**Comment by amjltc295** [comment]
RefineNet is not used for our model for now. It was designed for some baselines that use 2-stage architecture. If you want to give it a try, you may modify the concatenation code.

**Comment by bornabesic** [comment]
Thank you very much for your fast response!

In order to reproduce [Learnable Gated Temporal Shift Module for Deep Video Inpainting](https://arxiv.org/abs/1907.01131) paper, I should pre-train the "coarse" net with L1, perceptual and style losses and then fine-tune it with all the losses, including the TSMGAN loss?

**Comment by amjltc295** [comment]
> Thank you very much for your fast response!
> 
> In order to reproduce [Learnable Gated Temporal Shift Module for Deep Video Inpainting](https://arxiv.org/abs/1907.01131) paper, I should pre-train the "coarse" net with L1, perceptual and style losses and then fine-tune it with all the losses, including the TSMGAN loss?

All the losses mentioned in the paper. At the fin-tuning stage, you should set `temporal_discriminator` in config.json to `true` and set corresponding parameters in `d_t_args`. Then, set the `loss_gan_temporal_weight` to a proper value > 0.

**Comment by bornabesic** [comment]
[https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/video_inpainting_model.py#L58](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/4ee6d31c972571300b6a3ea4b262a86e3a923b07/src/model/video_inpainting_model.py#L58)
Is `conv_type='2d'` supposed to be `conv_type='vanilla'`?
Because `BaseModule` handles only `gated`, `partial` or `vanilla`.
