### ISSUE TITLE
What's the mearning of Version"Zero" and"circulant"?

### ISSUE THREAD

**Issue by Amazingren** [amjltc295/Free-Form-Video-Inpainting#12]
I am not clear about the two version used in you TSM, 
(1)What's the mearning of of Zero and Circulant?
different pading style?
(2)The the learnable can be understant in your code?
I am a  greenhand in code and this field, thank you very much and I am looking forward your reply and patience.
That's all~

**Comment by bornabesic** [comment]
gg bro

**Comment by Amazingren** [comment]
> gg bro

GG
