### ISSUE TITLE
model error

### ISSUE THREAD

**Issue by summerwbb** [amjltc295/Free-Form-Video-Inpainting#14]
hi !
when i run train.py with test mode i get this error:

Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main(config, args.resume, args.output_root_dir, args.pretrained_path)
  File "train.py", line 103, in main
    pretrained_path=pretrained_path
  File "/Users/momo/Desktop/code/inpainting/Free-Form-Video-Inpainting-master/src/trainer/trainer.py", line 33, in __init__
    pretrained_path
  File "/Users/momo/Desktop/code/inpainting/Free-Form-Video-Inpainting-master/src/base/base_trainer.py", line 67, in __init__
    self._resume_checkpoint(resume)
  File "/Users/momo/Desktop/code/inpainting/Free-Form-Video-Inpainting-master/src/base/base_trainer.py", line 194, in _resume_checkpoint
    self.model.load_state_dict(checkpoint['state_dict'])
  File "/Users/momo/miniconda2/envs/CRAFT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VideoInpaintingModel:
	Missing key(s) in state_dict: "generator.coarse_net.downsample_module.conv1.featureConv.weight", "generator.coarse_net.downsample_module.conv1.gatingConv.weight", "generator.coarse_net.downsample_module.conv2.featureConv.weight", "generator.coarse_net.downsample_module.conv2.gatingConv.weight", "generator.coarse_net.downsample_module.conv3.featureConv.weight", "generator.coarse_net.downsample_module.conv3.gatingConv.weight", "generator.coarse_net.downsample_module.conv4.featureConv.weight", "generator.coarse_net.downsample_module.conv4.gatingConv.weight", "generator.coarse_net.downsample_module.conv5.featureConv.weight", "generator.coarse_net.downsample_module.conv5.gatingConv.weight", "generator.coarse_net.downsample_module.conv6.featureConv.weight", "generator.coarse_net.downsample_module.conv6.gatingConv.weight", "generator.coarse_net.downsample_module.dilated_conv1.featureConv.weight", "generator.coarse_net.downsample_module.dilated_conv1.gatingConv.weight", "generator.coarse_net.downsample_module.dilated_conv2.featureConv.weight", "generator.coarse_net.downsample_module.dilated_conv2.gatingConv.weight", "generator.coarse_net.downsample_module.dilated_conv3.featureConv.weight", "generator.coarse_net.downsample_module.dilated_conv3.gatingConv.weight", "generator.coarse_net.downsample_module.dilated_conv4.featureConv.weight", "generator.coarse_net.downsample_module.dilated_conv4.gatingConv.weight", "generator.coarse_net.downsample_module.conv7.featureConv.weight", "generator.coarse_net.downsample_module.conv7.gatingConv.weight", "generator.coarse_net.downsample_module.conv8.featureConv.weight", "generator.coarse_net.downsample_module.conv8.gatingConv.weight", "generator.coarse_net.upsample_module.deconv1.conv.featureConv.weight", "generator.coarse_net.upsample_module.deconv1.conv.gatingConv.weight", "generator.coarse_net.upsample_module.conv9.featureConv.weight", "generator.coarse_net.upsample_module.conv9.gatingConv.weight", "generator.coarse_net.upsample_module.deconv2.conv.featureConv.weight", "generator.coarse_net.upsample_module.deconv2.conv.gatingConv.weight", "generator.coarse_net.upsample_module.conv10.featureConv.weight", "generator.coarse_net.upsample_module.conv10.gatingConv.weight", "temporal_discriminator.conv1.featureConv.weight", "temporal_discriminator.conv2.featureConv.weight", "temporal_discriminator.conv3.featureConv.weight", "temporal_discriminator.conv4.featureConv.weight", "temporal_discriminator.conv5.featureConv.weight".
	Unexpected key(s) in state_dict: "generator.coarse_net.downsample_module.conv1.featureConv.weight_v", "generator.coarse_net.downsample_module.conv1.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv2.featureConv.weight_v", "generator.coarse_net.downsample_module.conv2.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv3.featureConv.weight_v", "generator.coarse_net.downsample_module.conv3.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv4.featureConv.weight_v", "generator.coarse_net.downsample_module.conv4.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv5.featureConv.weight_v", "generator.coarse_net.downsample_module.conv5.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv6.featureConv.weight_v", "generator.coarse_net.downsample_module.conv6.gatingConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv1.featureConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv1.gatingConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv2.featureConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv2.gatingConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv3.featureConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv3.gatingConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv4.featureConv.weight_v", "generator.coarse_net.downsample_module.dilated_conv4.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv7.featureConv.weight_v", "generator.coarse_net.downsample_module.conv7.gatingConv.weight_v", "generator.coarse_net.downsample_module.conv8.featureConv.weight_v", "generator.coarse_net.downsample_module.conv8.gatingConv.weight_v", "generator.coarse_net.upsample_module.deconv1.conv.featureConv.weight_v", "generator.coarse_net.upsample_module.deconv1.conv.gatingConv.weight_v", "generator.coarse_net.upsample_module.conv9.featureConv.weight_v", "generator.coarse_net.upsample_module.conv9.gatingConv.weight_v", "generator.coarse_net.upsample_module.deconv2.conv.featureConv.weight_v", "generator.coarse_net.upsample_module.deconv2.conv.gatingConv.weight_v", "generator.coarse_net.upsample_module.conv10.featureConv.weight_v", "generator.coarse_net.upsample_module.conv10.gatingConv.weight_v", "temporal_discriminator.conv1.featureConv.weight_v", "temporal_discriminator.conv2.featureConv.weight_v", "temporal_discriminator.conv3.featureConv.weight_v", "temporal_discriminator.conv4.featureConv.weight_v", "temporal_discriminator.conv5.featureConv.weight_v".
(CRAFT) bogon:src momo$ python3 train.py -r /Users/momo/Desktop/code/inpainting/Free-Form-Video-Inpainting-master/v0.2.3_GatedTSM_inplace_noskip_b2_back_L1_vgg_style_TSMSNTPD128_1_1_10_1_VOR_allMasks_load135_e135_pdist0.1256.pth  --dataset_config other_configs/inference_example.json -od test_outputs  -p ../vgg16-397923af.pth

what shold do for this?

**Comment by amjltc295** [comment]
It seems that you have the wrong PyTorch version or a compatibility issue
