### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by AmingWu** [amjltc295/Free-Form-Video-Inpainting#16]
Could I use a 1080ti GPU to train your model? Thank you

**Comment by amjltc295** [comment]
Yes, you could adjust the batch size and video length. However, the performance would not be as good.

**Comment by AmingWu** [comment]
If I want to reproduce your result, how much GPU memory should I need? and how long your model needs to train?

**Comment by amjltc295** [comment]
We use two V100s with 16G rams. It takes 1-3 days for LGTSM and 3-10 days for 3DGated including fine-tuning with GAN.
