### ISSUE TITLE
Training Time for ICCV 2019 Method

### ISSUE THREAD

**Issue by harsh-99** [amjltc295/Free-Form-Video-Inpainting#18]
Hi, 

Thanks for sharing your code. I am working on the same dataset FVI.  I just wanted to know for how long did you trained the network and you have mentioned that you have used 1940 video and then applied a few data augmentation techniques. Did you apply data augmentation on all the videos? Can you please mention the final size of the dataset after augmentation? Also, It would be a great help if you can mention the weight of different losses (i.e. perceptual, style, reconstruction and adversarial) you used while training. 

Looking for your help

**Comment by amjltc295** [comment]
1. The free-form mask itself is the augmentation. There are only 1940 videos for training. For other augmentation, please refer to the code.
2. About 1/1/10/120/0.1 for recon/masked-recon/perc/style/adv.
