### ISSUE TITLE
Confusions about the pretrained weight

### ISSUE THREAD

**Issue by BostonLobster** [amjltc295/Free-Form-Video-Inpainting#22]
Hi, authors. Thanks for your splendid works.

I want to test your code with your provided pretrained weights, but I am confused of their naming. I saw two weights in the shared Google drive folder, but which one is for the FaceForensics dataset? Which for the FFVI dataset?

**Comment by amjltc295** [comment]
Hi, sorry for the confusing naming. They are both trained on the FVI dataset, for the two papers, respectively. For the LGTSM model of the FaceForensics dataset, please see https://drive.google.com/open?id=15eaQuF_bZOMuKt9-VoioZ5qCkGn7rzAm
