### ISSUE TITLE
Can't reproduce inference results for LGTSM in paper

### ISSUE THREAD

**Issue by Mykheievskyi** [amjltc295/Free-Form-Video-Inpainting#24]
Thanks for sharing your code. I try to reproduce inference results with pre-trained weights (weights for the BMVC 2019 work)  and get only **7 FPS** on GTX 1080Ti. In the [paper](https://arxiv.org/pdf/1907.01131.pdf) you report **80 FPS** for LGTMS solution, can you tell me what conditions these results were obtained?

**Comment by amjltc295** [comment]
For all models, we use a single Tesla V100 GPU with a Intel(R) Xeon(R) CPU E5-2650. We run the FVI dataset where video length is 15 frames at most. I forgot the batch size (should be 1~3), but you could test the relative time compared to other models and it should be accurate as we compare them with the same setting.
