### ISSUE TITLE
Problem in Environment Setup

### ISSUE THREAD

**Issue by kedarSedai** [amjltc295/Free-Form-Video-Inpainting#26]
when I enter this command conda env create -f environment.yaml
I got

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:

  - ffmpeg==4.0.2=ha0c5888_2
  - libxml2==2.9.8=h422b904_5
  - libxcb==1.13=h470a237_2
  - xorg-renderproto==0.11.1=h470a237_2
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libgfortran==3.0.0=1
  - pixman==0.34.0=h470a237_3
  - xorg-libxdmcp==1.1.2=h470a237_7
  - xorg-libx11==1.6.6=h470a237_0
  - tornado==5.1.1=py37h7b6447c_0
  - py-opencv==3.4.2=py37hb342d67_1
  - fontconfig==2.13.1=h65d0f4c_0
  - numpy==1.15.4=py37h1d66e8a_0
  - libffi==3.2.1=hd88cf55_4
  - zlib==1.2.11=h7b6447c_3
  - xorg-kbproto==1.0.7=h470a237_2
  - libgcc-ng==8.2.0=hdf63c60_1
  - cffi==1.11.5=py37he75722e_1
  - torchvision==0.2.1=py37_1
  - xorg-libice==1.0.9=h470a237_4
  - xorg-libxext==1.3.3=h470a237_4
  - harfbuzz==1.9.0=h04dbb29_1
  - gmp==6.1.2=hfc679d8_0
  - scipy==1.1.0=py37hfa4b5c9_1
  - nettle==3.3=0
  - sip==4.18.1=py37hf484d3e_2
  - freeglut==3.0.0=hfc679d8_5
  - mkl_fft==1.0.6=py37h7dd41cf_0
  - dbus==1.13.2=h714fa37_1
  - freetype==2.9.1=h8a8886c_1
  - opencv==3.4.2=py37h6fd60c2_1
  - expat==2.2.6=he6710b0_0
  - libiconv==1.15=h470a237_3
  - libopencv==3.4.2=hb342d67_1
  - libtiff==4.0.9=he85c1e1_2
  - openh264==1.8.0=hd28b015_0
  - xorg-libxrender==0.9.10=h470a237_2
  - xorg-libsm==1.2.3=h8c8a85c_0
  - tk==8.6.8=hbc83047_0
  - openssl==1.1.1a=h7b6447c_0
  - pthread-stubs==0.4=h470a237_1
  - gstreamer==1.14.0=hb453b48_1
  - pyqt==5.6.0=py37h22d08a2_6
  - graphite2==1.3.12=hfc679d8_1
  - libpng==1.6.35=hbc83047_0
  - glib==2.56.2=h464dc38_1
  - libglu==9.0.0=hfc679d8_0
  - pillow==5.3.0=py37hc736899_0
  - xz==5.2.4=h14c3975_4
  - scikit-image==0.14.0=py37hf484d3e_1
  - xorg-xproto==7.0.31=h470a237_7
  - kiwisolver==1.0.1=py37hf484d3e_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - xorg-xextproto==7.3.0=h470a237_2
  - sqlite==3.25.3=h7b6447c_0
  - pytorch==1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - mkl_random==1.0.1=py37h4414c95_1
  - icu==58.2=hfc679d8_0
  - pywavelets==1.0.1=py37hdd07704_0
  - cairo==1.14.12=h276e583_5
  - hdf5==1.10.2=hc401514_2
  - jasper==2.0.14=h07fcdf6_1
  - ninja==1.8.2=py37h6bb024c_1
  - xorg-libxau==1.0.8=h470a237_6
  - bzip2==1.0.6=h470a237_2
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - matplotlib==2.2.2=py37hb69df0a_2
  - gnutls==3.5.19=h2a4e5f8_1
  - ncurses==6.1=he6710b0_1
  - python==3.7.1=h0371630_3
  - libedit==3.1.20170329=h6b74fdf_2
  - gettext==0.19.8.1=h5e8e0c9_1
  - numpy-base==1.15.4=py37h81de0dd_0
  - pcre==8.42=h439df22_0
  - x264==1!152.20180717=h470a237_1
  - jpeg==9c=h470a237_1
  - readline==7.0=h7b6447c_5
  - qt==5.6.3=h8bf5577_3

What might be the issues?

**Comment by amjltc295** [comment]
Did you use macOS? The environment is tested in Linux 16.04+. If it fails, you could install the dependencies one by one by yourself.

**Comment by amjltc295** [comment]
And if you found the environment.yaml is outdated, feel free to send a PR to update it
