### ISSUE TITLE
May be a error in GAN training procedure.

### ISSUE THREAD

**Issue by facetohard** [amjltc295/Free-Form-Video-Inpainting#32]
In your training procedure, you updated G first and then updated D.
I think the reason is to save GPU memory. But It may be wrong against the principle of discriminating learning. 
Updating D net first to find the minimal or optimal value that measure the divergence of distribution between real and fake data. 
But in your procedure, you update G first by latest D net's parameters. It may trains successfully with LSGAN, but gets enormous value with hinge loss in my experiments. 
Though the results are not too bad with LSGAN, the temporal GAN loss will be constant after some iterations.
I think the reason is what I have pointed and I have done some experiments to verify.

**Comment by amjltc295** [comment]
Could you show some experimental results that fix this problem? I would love to see improvements for current training procedure. You're more than welcome to do code change and send a PR for this
