### ISSUE TITLE
confusion about discriminator network 

### ISSUE THREAD

**Issue by FYtrace** [amjltc295/Free-Form-Video-Inpainting#34]
Hi Ya-Liang, thanks for your wonderful sharing. I was a little confused during the fine-tune stage.  Both spatial_discriminator and temporal_discriminator should be involved？ There seems to be a dimension error when initializing the spatial-discriminator network.
please refer to:  https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/e0c9a98995c85d4b6abe2f447639bcc319bd245d/src/model/video_inpainting_model.py#L59

Secondly，should the non-gan losses (weight) settings in the pretrained stage keep the same in the fine-tune stage?

Thanks~

**Comment by yuyang16101066** [comment]
It seems that there is no conv_type corresponding to '2d' in BaseModule class, so spatial _discriminator object has no ConvBlock attribute.

**Comment by yuyang16101066** [comment]
I think conv_type='2d' should be conv_by='2d' and xs_t = torch.transpose(xs, 1, 2) in line 157 of networks.py should be removed.

**Comment by amjltc295** [comment]
1. Only temporal_discriminator should be enough
2. Yes
