### ISSUE TITLE
Cannot download the I3d pretrained model for FID score

### ISSUE THREAD

**Issue by hitachinsk** [amjltc295/Free-Form-Video-Inpainting#37]
Hello, I learned a lot from your codes and your paper, thank you! However, when I tried to run your codes and evaluate the FID score, I found I was forbidden by the website you leave for downloading the i3d model (http://www.cmlab.csie.ntu.edu.tw/~zhe2325138/i3d_rgb_imagenet.pt), do you have other link for downloading this model? Thanks and I'm looking for your reply.

**Comment by amjltc295** [comment]
See https://github.com/amjltc295/Free-Form-Video-Inpainting/issues/28

**Comment by hitachinsk** [comment]
Thanks a lot, god bless you.
