### ISSUE TITLE
About I3D model for VFID score.

### ISSUE THREAD

**Issue by kyuyeonpooh** [amjltc295/Free-Form-Video-Inpainting#42]
Hi, thanks for sharing great codes!

I have a question about the mode (training / testing) you have used for I3D networks for evaluating VFID score.

https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/19bfc6fbe626385be549ea2fc6c1ba7852e48e56/src/evaluate.py#L35-L48
As shown above in I3D model initialization part for I3D feature extracting, it seems that you haven't converted the model into evaluation mode by `i3d_model.eval()`.

When I evaluate your model without converting I3D into `eval` mode, I was able to reproduce the similar results in the paper.
However, when I turned the model into evaluation mode (because using `.eval()` is common for using the model as feature extractor), I found the VFID score goes up to over 1.0.

Is there any reason why the I3D network is used as training mode?
Thank you for reading! Have a nice day.

**Comment by caimaomao315** [comment]
Hello, I have been reading your article and code recently,
But I encountered a series of problems with FID, and the answerer mentioned it and solved it according to the comments.
But I still get the following error:
{evaluate.py:40} INFO - Loading I3D model for FID score ..
{trainer.py:438} ERROR - cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/THCBlas.cu:116
Traceback (most recent call last):`
![屏幕截图 2022-05-10 201148](https://user-images.githubusercontent.com/61854190/167625421-8bb3499a-813c-4b88-8a2e-405459d7e28b.jpg)
