### ISSUE TITLE
can't find the code which related to the learnable  temporal shift kernel

### ISSUE THREAD

**Issue by deepcs233** [amjltc295/Free-Form-Video-Inpainting#5]
Hi, Thanks for your code.
I can't find the code which related to the **learnable**  temporal shift kernel. I only find the original TSM Code from `Song Han`, can you tell me where is?
Thanks very much

**Comment by Nash2325138** [comment]
You need to change the branch to `LGTSM` and find the class `LearnableTSM` in `src/model/tsm_utils.py`

**Comment by Nash2325138** [comment]
I'll close this issue now if you have no further questions :)
