### ISSUE TITLE
Evaluation details

### ISSUE THREAD

**Issue by 1900zyh** [amjltc295/Free-Form-Video-Inpainting#6]
Dear authors,

Thank you for sharing! 
I have a question that, do you test all frames in the test set for each sample?
According to [dataset.py](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/master/src/data_loader/dataset.py#L106) and [inference.config](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/master/src/other_configs/inference_example.json#L27), it seems that you only evaluate on former 15 frames of each video. 

BTW, the model takes n frames as input and outputs n frames, so for each video how do you deal with overlapping frames?

**Comment by amjltc295** [comment]
> Dear authors,
> 
> Thank you for sharing!
> I have a question that, do you test all frames in the test set for each sample?
> According to [dataset.py](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/master/src/data_loader/dataset.py#L106) and [inference.config](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/master/src/other_configs/inference_example.json#L27), it seems that you only evaluate on former 15 frames of each video.
That's true. For the FVI dataset, we only test the begging 15 frames for each video.

> BTW, the model takes n frames as input and outputs n frames, so for each video how do you deal with overlapping frames?
We didn't actually test long videos but simply takes all frames as input and outputs all result frames as the GPU memory is enough for 15 frames.  For longer duration, I suppose 2~3 overlapping is enough, but you could do some experiments yourself. Looking forward to seeing your results.

**Comment by SURABHI-GUPTA** [comment]
@zengyh1900 How did you manage to run the inference code?
