### ISSUE TITLE
super resolution problem

### ISSUE THREAD

**Issue by Kim9878** [amjltc295/Free-Form-Video-Inpainting#7]
Hello, when I tried to test my own testing data and set the type to super resolution, I always got a bad result. Could you please tell me how to set the json file when I want to use super resolution type to test my video? Thanks!

**Comment by amjltc295** [comment]
> Hello, when I tried to test my own testing data and set the type to super resolution, I always got a bad result. Could you please tell me how to set the json file when I want to use super resolution type to test my video? Thanks!

You need to train another model for video super-resolution, as it is with a different pattern of mask.
