### ISSUE TITLE
training codes for ICCV19's work

### ISSUE THREAD

**Issue by 1900zyh** [amjltc295/Free-Form-Video-Inpainting#8]
Hi @amjltc295 ,

I saw that you have released an implementation of the model proposed in ICCV2019.  [video-inpainting-model.py](https://github.com/amjltc295/Free-Form-Video-Inpainting/blob/master/src/model/video_inpainting_model.py).  
I trained it on YouTube-VOS with object-like masks. However, the results are very blurred and I'm unable to reproduce the results shown in your paper. 

Would you mind sharing completed training codes (especially weights of different losses)?
I would strongly appreciate any helps from you!

Thanks!

**Comment by amjltc295** [comment]
Hi,

We had a slightly different code for the ICCV2019 work. It is rather messy now, but we will organize and release it later.
The training procedure is basically the same but it takes significantly more time. As the performance is quite similar, we recommend using the BMVC model in general.

**Comment by amjltc295** [comment]
Fixed by #21
