### ISSUE TITLE
pretrained weights in LGTSM

### ISSUE THREAD

**Issue by ValentiaSulli** [amjltc295/Free-Form-Video-Inpainting#9]
Hi,
it seems that there is no corresponding pretrained model to the latest work LGTSM, just the pretrained model in ICCV2019's work. Could you please provide the pretrained LGTSM model? 

Thanks!

**Comment by amjltc295** [comment]
Hi, the file is actually the pretrained weights of the LGTSM work, while we are still organizing source code for the ICCV one (see #8 )
